save_chat: true
text_model_path: mistralai/Mistral-7B-Instruct-v0.3
code_model_path: Qwen/Qwen2.5-Coder-7B-Instruct
vision_model_path: Qwen/Qwen2.5-VL-7B-Instruct
device: cuda
provider: "transformers"
